services:

  resume-make:
    build:
      context: .
      dockerfile: ./.docker/resume.dockerfile
    container_name: resume-make
    image: resume-make
    working_dir: /home/app/resume
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - TEXMFCACHE=/tmp/texmf-cache
    volumes:
      - ./:/home/app/resume:z
    command: sh -c "make all"
