services:

  resume-make:
    build:
      context: .
      dockerfile: ./.docker/resume.dockerfile
    container_name: resume-make
    image: resume-make
    working_dir: /home/app/resume
    volumes:
      - ./:/home/app/resume:z
    command: sh -c "make all"
